apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elk-stack
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    cluster.name: "eks-logging"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
