apiVersion: v1
kind: Pod
metadata:
  name: counter
  namespace: elk-stack
  labels:
    app: counter
spec:
  containers:
  - name: counter
    image: busybox
    args:
    - /bin/sh
    - -c
    - |
      i=0
      while true; do
        echo "$(date) - Counter value: $i"
        i=$((i+1))
        sleep 5
      done

